# Die 207 häufigsten deutschen Wörter nach:
# https://de.wikipedia.org/wiki/Liste_der_h%C3%A4ufigsten_W%C3%B6rter_der_deutschen_Sprache

most_frequent_german_words = [
    'DIE', 'DER', 'UND', 'IN', 'ZU', 'DEN', 'DAS', 'NICHT', 'VON', 'SIE',
    'IST', 'DES', 'SICH', 'MIT', 'DEM', 'DASS', 'ER', 'ES', 'EIN', 'ICH',
    'AUF', 'SO', 'EINE', 'AUCH', 'ALS', 'AN', 'NACH', 'WIE', 'IM', 'FUER',

    'MAN', 'ABER', 'AUS', 'DURCH', 'WENN', 'NUR', 'WAR', 'NOCH', 'WERDEN', 'BEI',
    'HAT', 'WIR', 'WAS', 'WIRD', 'SEIN', 'EINEN', 'WELCHE', 'SIND', 'ODER', 'ZUR',
    'UM', 'HABEN', 'EINER', 'MIR', 'UEBER', 'IHM', 'DIESE', 'EINEM', 'IHR', 'UNS',
    'DA', 'ZUM', 'KANN', 'DOCH', 'VOR', 'DIESER', 'MICH', 'IHN', 'DU', 'HATTE',
    'SEINE', 'MEHR', 'AM', 'DENN', 'NUN', 'UNTER', 'SEHR', 'SELBST', 'SCHON', 'HIER',
    'BIS', 'HABE', 'IHRE', 'DANN', 'IHNEN', 'SEINER', 'ALLE', 'WIEDER', 'MEINE', 'ZEIT',
    'GEGEN', 'VOM', 'GANZ', 'EINZELNEN', 'WO', 'MUSS', 'OHNE', 'EINES', 'KOENNEN', 'SEI',

    'JA', 'WURDE', 'JETZT', 'IMMER', 'SEINEN', 'WOHL', 'DIESES', 'IHREN', 'WUERDE', 'DIESEN',
    'SONDERN', 'WEIL', 'WELCHER', 'NICHTS', 'DIESEM', 'ALLES', 'WAREN', 'WILL', 'HERR', 'VIEL',
    'MEIN', 'ALSO', 'SOLL', 'WORDEN', 'LASSEN', 'DIES', 'MACHEN', 'IHRER', 'WEITER', 'LEBEN',
    'RECHT', 'ETWAS', 'KEINE', 'SEINEM', 'OB', 'DIR', 'ALLEN', 'GROSSEN', 'JAHRE', 'WEISE',
    'MUESSEN', 'WELCHES', 'WAERE', 'ERST', 'EINMAL', 'MANN', 'HAETTE', 'ZWEI', 'DICH', 'ALLEIN',
    'HERREN', 'WAEHREND', 'PARAGRAPH', 'ANDERS', 'LIEBE', 'KEIN', 'DAMIT', 'GAR', 'HAND', 'HERRN',
    'EUCH', 'SOLLTE', 'KONNTE', 'ERSTEN', 'DEREN', 'ZWISCHEN', 'WOLLEN', 'DENEN', 'DESSEN', 'SAGEN',
    'BIN', 'MENSCHEN', 'GUT', 'DARAUF', 'WURDEN', 'WEISS', 'GEWESEN', 'SEITE', 'BALD', 'WEIT',
    'GROSSE', 'SOLCHE', 'HATTEN', 'EBEN', 'ANDERN', 'BEIDEN', 'MACHT', 'SEHEN', 'GANZE', 'ANDEREN',
    'LANGE', 'WER', 'IHREM', 'ZWAR', 'GEMACHT', 'DORT', 'KOMMEN', 'WELT', 'HEUTE', 'FRAU',
    'WERDE', 'DERSELBEN', 'GANZEN', 'DEUTSCHEN', 'LAESST', 'VIELLEICHT', 'MEINER',
]


letter_probability_in_german_texts = dict(
    E = 17.29,
    N =  9.72,
    S =  7.84,
    I =  7.5 ,
    R =  6.96,
    A =  6.47,
    T =  6.11,
    D =  5.05,
    H =  4.73,
    U =  4.32,
    L =  3.42,
    C =  3.04,
    G =  2.99,
    M =  2.51,
    O =  2.49,
    B =  1.88,
    W =  1.88,
    F =  1.65,
    K =  1.2 ,
    Z =  1.12,
    P =  0.79,
    V =  0.67,
    J =  0.27,
    Y =  0.04,
    X =  0.03,
    Q =  0.02,
)


cypher = (
"LKGIBJP AKVB JLJRP FJX VNA SXNTNPZOVX PZOXNCTPTVBBVX VX FGXLV MKX JBBVR RNT LVX "
"PJTNXNPZOVA PZNVAZV CNZTNKA XVNOV HVX JAOJBTVX LGXZO LNV IJBJWNP SVUJAAT JLJRP "
"UJR JBP PKOA MKA DJAVT NA LVX VAIBNPZOVA GANMVXPNTJVTPPTJLT ZJRSXNLIV YGX FVBT "
"AJZO LVX PZOVNLGAI PVNAVX VBTVXA YKI LNV RGTTVX RNT LVR CGVACDJVOXNIVA LKGIBJP "
"AJZO SXVATFKKL NA VPPVW LKXT FGZOP VX IVRVNAPJR RNT PVNAVX DGVAIVXVA PZOFVPTVX "
"JGC AVGAYVOAOGALVXTMNVXGALPVZOYNI OVNXJTVTV PVNAV RGTTVX VNA YFVNTVP RJB JGP "
"LNVPVX VOV PTJRRTVA YFVN DGVAIVXV OJBSIVPZOFNPTVX JS "
"AVGAYVOAOGALVXTAVGAGALCGVACYNI SVPGZOTV JLJRP LNV SXVATFKKL PZOKKB FK VX MKX "
"JBBVR JA LVA AJTGXFNPPVAPZOJCTVA NATVXVPPNVXT FJX LJRJBP SVIJAA VX PNZO JBP "
"JGTKX YG SVTJVTNIVA FKSVN VX RNT PVNAVA TVWTVA JGC IXKPPV YGPTNRRGAI LVP "
"BVOXHVXPKAJBP PTNVPP GAL VNAVA BNTVXJTGXFVTTSVFVXS IVFJAA PVNA VXPTVX "
"MVXKVCCVATBNZOTVX TVWT FJX VNAV UKRNPZOV UGXYIVPZONZOTV GVSVX VNAVA RJAA LVX "
"PVNA IVLJVZOTANP NA LVX BKALKAVX G SJOA MVXBKX GAL PNZO NR CGALSGVXK LJAJZO "
"VXUGALNITV LNVPVX TVWT FGXLV NA VNAVX PZNVAZVCNZTNKAYVNTPZOXNCT CGVX DGIVALBNZOV "
"MVXKVCCVATBNZOT PHJVTVX PTGLNVXTV VX JBP RNTIBNVL LVP PT DKOAP ZKBBVIVP VAIBNPZO "
"NA ZJRSXNLIV FK VX PNZO VNAVX UBVNAVA UKRNUVXIXGHHV AJRVAP ZGBVP JAPZOBKPP LKXT "
"BVXATV VX DKOA BBKQL UVAAVA RNT LVR VX PNZO PHJVTVX VNAV FKOAGAI TVNBTV FJVOXVAL "
"PVNAVP PTGLNGRP JXSVNTVTV VX JBP JGPONBCPUXJCT GR PNZO PVNA JGPIVLVOATVP TXJRHVA "
"LGXZO VGXKHJ YG CNAJAYNVXVA JGC VNAVX LNVPVX XVNPVA VATPTJAL JGZO LNV NLVV YG "
"PVNAVR SVXGVORTVPTVA FVXU HVX JAOJBTVX LGXZO LNV IJBJWNP LNV NLVV UJR NOR JBP VX "
"FNV VX LVX SSZ SVPZOXNVS AJZO VNAVR UAVNHVASVPGZO NA NAAPSXGZU JAIVTXGAUVA JGC "
"VNAVR JZUVX BJI GAL NA LNV PTVXAV PZOJGTV VX PVBSPT SVPZOXNVS LNVPVP VXVNIANP PK "
"LNV NLVV CGVX LVA TNTVB UJR RNX AVGAYVOAOGALVXTVNAGALPNVSYNI JBP NZO SVTXGAUVA "
"JGC VNAVR CVBL NA NAAPSXGZU BJI ANZOT XNZOTNI SVTXGAUVA AGX IVXJLV PK SVTXGAUVA "
"FNV RJA AJZO VNA HJJX PTJXUVA IKVPPVXA FNXL FVAA RJA YFVN IJAYV TJIV ANZOTP "
"IVIVPPVA OJT FJVOXVAL PVNAVX PTGLNVAYVNT JXSVNTVTV JLJRP NA VNAVX JALVXVA "
"GANMVXPNTJVXVA ZKRVLQIXGHHV AJRVAP CKKTBNIOTP RNT LNV VTFJ VNA DJOXYVOAT CXGVOVX "
"JGZO LVX UXNPTJBBNPJTNKAPHGAUT CGVX LNV UKRNUVXIXGHHV RKATQ HQTOKA IVFVPVA FJX "
"SVN LVX VX PNRKA DKAVP UVAAVABVXATV RNT LVR VX PHJVTVX YGPJRRVAJXSVNTVTV "
"AVGAYVOAOGALVXTMNVXGALPNVSYNI MVXBNVPP JLJRP LJP ZKBBVIV RNT LVR CVPTVA MKXPJTY "
"PZOXNCTPTVBBVX YG FVXLVA JACJAIP IVBJAI NOR LJP AGX RJVPPNI VXCKBIXVNZO GATVX "
"JALVXVR JXSVNTVTV VX RNT IXJOJR ZOJHRJA MKA RKATQ HQTOKA YGPJRRVA NA CKBIV "
"YFVNGALMNVXNI MKA RKATQ HQTOKAP CBQNAI ZNXZGP TXJT VX NA VNAVX AVSVAXKBBV JGC JA "
"LVX BVTYTVA CKBIV HJXTQ HKBNTNZJB SXKJLZJPT KA SVOJBC KC TOV BNSVXJB HJXTQ "
"FNXUTV VX JBP JGTKX RNT AVGAYVOAOGALVXTPNVSVAGALPNVSYNI IVBJAI NOR LVX "
"LGXZOSXGZO JBP VX RNT PNRKA SXVTT VNAVA MVXTXJI GVSVX LNV JGPPTXJOBGAI VNAVX "
"PZNVAZV CNZTNKA XJLNKPVALGAI JSPZOBKPP LNV PVALGAI TXGI LVA TNTVB TOV "
"ONTZOONUVXP IGNLV TK TOV IJBJWQ GAL FGXLV YGR VXPTVA RJB "
"AVGAYVOAOGALVXTJZOGALPNVSYNI MKR SXNTNPZOVA XJLNKPVALVX SSZ XJLNK MNVX IVPHNVBT "
"NA PTJXU MVXJVALVXTVX GAL VXFVNTVXTVX CKXR FGXLV LNV PVXNV YFNPZOVA "
"AVGAYVOAOGALVXTAVGAGALPNVSYNI GAL AVGAYVOAOGALVXTYFVNGALJZOYNI YGAJVZOPT JBP "
"TXNBKINV NA SGZOCKXR MVXKVCCVATBNZOT VNAV FVPVATBNZOV JVALVXGAI NPT LJP "
"VATCVXAVA JBBVX YGPJRRVA RNT DKOA BBKQL IVPZOXNVSVAVA JATVNBV LVX XJLNKPVALGAIVA "
"CGVAC GAL PVZOP LVX NAOJBT LVP GXPHXGVAIBNZOVA OKVXPHNVBP CNALVT PNZO MKX JBBVR "
"NR VXPTVA SJAL LNV SGVZOVX FGXLVA SVPTPVBBVX AVGAYVOAOGALVXTMNVXGALJZOYNI CKBITV "
"VNA MNVXTVX SJAL RJZOTP IGT GAL LJAUV CGVX LVA CNPZO "
"AVGAYVOAOGALVXTYFVNGALAVGAYNI VNA CGVACTVX RKPTBQ OJXRBVPP VNARJB XGHVXT GAL "
"YGXGVZU RNT LVR GATVXTNTVB CGVACTVX SJAL VNAVX MNVXTVNBNIVA TXNBKINV "
"AVGAYVOAOGALVXTVNAGALAVGAYNI OVNXJTVTV JLJRP DJAV SVBPKA "
"AVGAYVOAOGALVXTMNVXGALAVGAYNI FGXLV VNAV IVRVNAPJRV TKZOTVX IVSKXVA JACJAIP "
"BVSTV LNV CJRNBNV NA BKALKA AVGAYVOAOGALVXTAVGAGALAVGAYNI YKI JLJRP RNT PVNAVX "
"CJRNBNV AJZO UJBNCKXANVA MKX JBBVR LJRNT VX LNV MVXCNBRGAI MKA HVX JAOJBTVX "
"LGXZO LNV IJBJWNP CGVX LJP UNAK GATVXPTGVTYVA UKAATV JLJRP PTJXS JR VBCTVA RJN "
"YFVNTJGPVALGALVNAP NA VNAVR CNTAVPPPTGLNK JA VNAVR OVXYNACJXUT PVNA IXJS "
"SVCNALVT PNZO JGC LVR ONIOIJTV ZVRVTVXQ NA BKALKA YG PVNAVR IVLVAUVA CNALVT "
"DJVOXBNZO JR CGVACGALYFJAYNIPTVA RJN LVX PKIVAJAATV TKFVB LJQ OJALTGZOTJI PTJTT "
"LNV LKGIBJP JLJRP RVRKXNJB BVZTGXV NPT VNAV MKXTXJIPXVNOV LNV DJVOXBNZO YG VOXVA "
"LVP JGTKXP PTJTTCNALVT LVX MKXTXJI CNALVT PVNT YFVNTJGPVALGALLXVN DVLVP DJOX YGX "
"GATVXPTGVTYGAI MKA GRFVBTKXIJANPJTNKAVA FNV PJMV TOV XONAK NATVXAJTNKAJB PTJTT "
"GAL SVOJALVBT TOVRVA FNV FNPPVAPZOJCT VXCKXPZOGAI AJTGXPZOGTY GAL ZKRVLQ LNV "
"MVXJAPTJBTGAI CNALVT TXJLNTNKAVBB JR VBCTVA RJVXY XGAL GR JLJRP IVSGXTPTJI PTJTT "
"GAL CNALVT LVXYVNT NA LVX XKQJB IVKIXJHONZJB PKZNVTQ PTJTT "
)
